### PR TITLE
refactor: Extract metric runner to it's own struct

### PR DESCRIPTION
**Pull request by vaerh**
I hope I didn't lose anything in the migration. But I need to debug it. My application crashed at startup with null pointer dereferencing.

### CODE REVIEW

**Comment by jlpedrosa** [comment]
It was in drat! I didn't get  the time to run/complete it!! 🤣  i wanted to start adding tests.

**Comment by vaerh** [comment]
Yeah, I saw it. I wondered if it would work out of the box.....

**Comment by jlpedrosa** [comment]
@vaerh  it would be super great if you can create a make target or somthing to run the qemu mikrotik router that you have for routeros.

**Comment by vaerh** [comment]
@jlpedrosa I'm having an overloaded weekend again. If possible please make a issue with all the items that need to be closed in order of priority. I'll try to start doing them starting tomorrow night.

**Comment by jlpedrosa** [comment]
@vaerh No worries whatsoever! There's absolutely no rush! This is a hobbie to enjoy, no need don't feel any pressure.

**Pull request closed without merging**
