### PR TITLE
Poc2

### PR DESCRIPTION
**Pull request by jlpedrosa**
Your code

### CODE REVIEW

**Comment by vaerh** [comment]
I'll recover a bit from the routeros and we'll continue.

**Comment by jlpedrosa** [comment]
No rush, I'm going crazy also here with my home lab.....

**Comment by vaerh** [comment]
No problem, I have a big workload too.

**Comment by jlpedrosa** [comment]
Hey! I'm kind of back. Should I review this and we adding features?

**Comment by vaerh** [comment]
I tried to remember where I left off last time, but I couldn't, there was a lot of code in that time.
The only two things that came to mind were that the current implementation doesn't take into account serving more than one router (the labels are static address and router name), and that I wanted to tackle CAPsMAN but didn't have time. Is it relevant to you?

**Comment by jlpedrosa** [comment]
Hey! no problem, we can fix it after the fact. We are not reelasing anything (yet).

The static router is an important thingy, we need to add a arg+env variable to set it up. Let me create later some issues what the items that needs to be done so we keep track of it.

**Pull request merged**
